### ISSUE TITLE
Q4 2020: refresh *.ocaml.org system infrastructure

### ISSUE THREAD

**Issue by avsm** [ocaml/v2.ocaml.org#1169]
The system infrastructure running the *.ocaml.org services has been tracked in a combination of private repositories and email lists. This ticket tracks the effort to shift this to a more centralised place on ocaml.org, and focusses on intended changes in the Q4 2020 timeframe.

This is partly to reflect the growth of the infrastructure and requests from more people to contribute to it, and also to make it easier to acknowledge the significant contributions from sponsors such as Packet.net, Scaleway, Rackspace, and Amazon towards it over the past eight years or so.  There are also separate groups of people who are starting to work on some of the new efforts, and so a tracking issue will provide a place to discuss new projects and discover what's going on.

The background to the infrastructure changes are in my OCaml Workshop 2020 talk ([slide 25](https://speakerdeck.com/avsm/ocaml-platform-2020?slide=25) or [video](https://www.youtube.com/watch?v=E8T_4zqWmq8&list=PLKO_ZowsIOu5fHjRj0ua7_QWE_L789K_f&index=1)). I'll be going through and creating a ticket per infrastructure change and editing the body of this issue as I do so.

- [x] docs.ocaml.org: incubate, plan (https://github.com/ocaml/ocaml.org/issues/1171)
- [x] git.ocaml.org: incubate, plan  (https://github.com/ocaml/ocaml.org/issues/1176)
- [x] inbox.ocaml.org : active, document migration from Rackspace (https://github.com/ocaml/ocaml.org/issues/1170)
- [x] lists.ocaml.org : sustain, notify community of possible temporary deprecation (https://github.com/ocaml/ocaml.org/issues/1170)
- [x] ci.ocaml.org : active, document migration to ocurrent from datakit-ci (https://github.com/ocaml/ocaml.org/issues/1177)
- [x] discuss.ocaml.org : active, acknowledge open source discount (https://github.com/ocaml/ocaml.org/issues/1174)
- [x] chat.ocaml.org: incubate, discuss (https://github.com/ocaml/ocaml.org/issues/1174)
- [x] discord.ocaml.org : active, document migration from Rackspace (https://github.com/ocaml/ocaml.org/issues/1175)
- [x] www.ocaml.org : active, document migration from Rackspace (https://github.com/ocaml/ocaml.org/issues/1178)
- [x] opam.ocaml.org : sustain, plan merger into ocaml.org (https://github.com/ocaml/ocaml.org/issues/1173)
- [x] forge.ocaml.org : deprecated, document history on ocaml.org (https://github.com/ocaml/ocaml.org/issues/1172)

If anyone else spots any missing gaps in the infrastructure list, please do feel free to comment on this issue or ping me directly on anil@recoil.org.
