### ISSUE TITLE
Want to help?  Here are some tasks!

### ISSUE THREAD

**Issue by Chris00** [ocaml/v2.ocaml.org#824]
Here are some tasks with some details about how to tackle them and possible references.  Do not forget to add your name to the [contributors page](http://ocaml.org/contributors.html) to showcase your efforts!  In addition to the whole community being thankful, contributors demonstrating a strong commitment for several months will be offered commit rights to the repository.
### Move the content of [opam.ocaml.org](https://opam.ocaml.org/) to `ocaml.org/opam/`
- [ ] Propose a design (mockups) for how the various menus would fit together.
- [ ] Once the mockups are accepted, modify the [opam.o.o maintenance scripts](https://github.com/ocaml/opam.ocaml.org) so they generate the proposed layout.
- [ ] Merge the opam.o.o scripts with those of o.o to generate the opam content.
- [ ] Adapt the [infrastructure scripts](https://github.com/ocaml/ocaml.org/issues/815) — note they `sync` with deletion if 2 different builds are used.
### Improve/restructure tutorials
- [x] The [install page](http://ocaml.org/docs/install.html) (also the [French one](http://ocaml.org/docs/install.fr.html)) should be updated.  See also https://github.com/ocaml/ocaml.org/issues/801
- [ ] Improve Faqs – https://github.com/ocaml/ocaml.org/issues/765 (should be easy).
- [ ] Pick up any tutorial and improve it.  For ideas, see e.g.,
  - [ ] https://github.com/ocaml/ocaml.org/issues/801 (Ubuntu installation), 
  - [ ] https://github.com/ocaml/ocaml.org/issues/739 (import lablgtk+ tutorial), 
  - [ ] https://github.com/ocaml/ocaml.org/issues/641 (translation), 
  - [ ] https://github.com/ocaml/ocaml.org/issues/627 (Weak module tutorial), 
  - [ ] https://github.com/ocaml/ocaml.org/issues/611 (basic tutorial for ocamlfind), 
  - [ ] https://github.com/ocaml/ocaml.org/issues/605 (fix links), 
  - [ ] https://github.com/ocaml/ocaml.org/issues/598 (Set tutorial), 
  - [ ] https://github.com/ocaml/ocaml.org/issues/500 (first step tutorial), 
  - [ ] https://github.com/ocaml/ocaml.org/issues/451 (polymorphic variants), 
  - [x] https://github.com/ocaml/ocaml.org/issues/450 (`;;` v.s. `;`)
  - [ ] https://github.com/ocaml/ocaml.org/issues/888 Gtk tutorial: must be updated to use the latest interface from `lablgtk`.
- [ ] Explain why there are several "standard libraries" and the philosophy behind them — helping the newcomers to choose.
- [ ] Pick a [topic here](https://discuss.ocaml.org/t/making-ocaml-accessible-and-learnable-for-more-people/381/6) and submit/replace the tutorial about it.
### Create thematic pages

For each of the topics below, list the various libraries that exists (should eventually be partly automated with opam tags), explain the strengths and weaknesses in order to help user to pick up the right one for him, for each of them show some code to get started,...  This may be one way to  [incorporate content from awesome-ocaml](https://github.com/ocaml/ocaml.org/issues/502).  Inspiration for the topics: [Python](https://www.python.org/about/apps/).
- [ ] OCaml for the web (ocamlnet, ocsigen, cohttp, typed HTML, js_of_ocaml,...)
- [ ] OCaml for science (lacaml, gls, sundialsml, root finding, lbfgs...)
- [ ] ...
### Improve the infrastructure
- [ ] Make a tool to report which translations are out of date (based on the Git history).  Use [OCaml Git](https://github.com/mirage/ocaml-git) for that.  Bonus points for showing the diff of the English version and opening an issue on Github.
- [ ] Given some meetup groups, extract the dates of the meetings (from iCal links?) and display them on the website.
- [ ] Separate the "Jobs" feeds (specific file alike `planet_feeds.txt`) and display them in another tab (next to _News_) on the front page and in another page in the planet (crosslinked with the planet).
- [ ] Make a bot for IRC that would help with basic questions (eventually using machine learning) and help to collect stats.
- [ ] Version control the [infrastructure scripts](https://github.com/ocaml/ocaml.org/issues/815) — needs to be done in close collaboration with a [member of OCaml.org team](http://ocaml.org/about.html#Governanceofthiswebsite).

**Comment by AltGr** [comment]
> ### Move the content of opam.ocaml.org to `ocaml.org/opam/`

Note that this is generated by [`opam2web`](https://github.com/ocaml/opam2web), and that there is some [administration](https://github.com/ocaml/opam.ocaml.org) involved (README slightly out of date). Although merging the design and layout of the two sites is a good idea, I am uncertain about that move.

Note that the site also includes the not-quite-dead [platform blog](https://opam.ocaml.org/blog) generated from [this repo](https://github.com/ocaml/platform-blog).

`https://opam.ocaml.org/` is also used by opam as the repository where packages are fetched from, and I don't think that would be wise to change. Administration scripts mentionned above mix updates of the package repository and the website.

**Comment by Chris00** [comment]
@AltGr Thanks for the information.  I am only talking about moving the web site part, not the data relevant to `opam` (and actually using opam.o.o to host backups of all packages, including their development repositories).  Changing the domain name for a part of the site is not good IMHO—in particular, if you pin a tab with o.o, going to _packages_ will open a new tab, which is confusing.

**Comment by amirmc** [comment]
> Move the content of `opam.ocaml.org` to `ocaml.org/opam/`

I think it's better to use something like `ocaml.org/pkg/`, or `ocaml.org/packages`, or similar.  This doesn't tie it to the name of the tool and is better in the long term.  The [original wireframes](http://amirchaudhry.com/wireframe-demos-for-ocamlorg) I put together had examples of how this might work (there are screencasts in the blog post but the online version is no longer available). If they're still useful we can figure out how to update them.

_example page_
![5_packages](https://cloud.githubusercontent.com/assets/121855/18086171/77d5e2dc-6ea6-11e6-9954-ad81ede6deca.png)

**Comment by agarwal** [comment]
> I think it's better to use something like ocaml.org/pkg/, or ocaml.org/packages, or similar

On the other hand, `opam` has some brand recognition. Maybe good to go with `ocaml.org/opam`.

**Comment by dbuenzli** [comment]
> On the other hand, opam has some brand recognition. Maybe good to go with ocaml.org/opam.

Good uris are independent from the underlying technology.

**Comment by agarwal** [comment]
> Good uris are independent from the underlying technology.

I thought about it more, and yes I think you're right.

**Comment by redianthus** [comment]
> The install page (also the French one) should be updated. See also #801

I think it's OK now and with #992.

**Comment by Riddhima23** [comment]
@Chris00 can I work on the issue of making a bot for IRC?
